name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          # Получаем последний git tag
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          
          # Увеличиваем патч
          IFS='.' read -r major minor patch <<<"${TAG#v}"
          patch=$((patch + 1))
          NEW_TAG="v${major}.${minor}.${patch}"
          
          # Проверяем, существует ли тег в удалённом
          if git ls-remote --tags origin | grep -q "refs/tags/$NEW_TAG"; then
            echo "Tag $NEW_TAG already exists, using commit SHA instead"
            NEW_TAG="${GITHUB_SHA::8}"  # первые 8 символов SHA
          fi
          
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Timeweb Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/user-service:latest
            ${{ secrets.REGISTRY_URL }}/user-service:${{ steps.version.outputs.new_tag }}


      - name: Create new git tag
        env:
          TAG: ${{ steps.version.outputs.new_tag }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG
          git push origin $TAG
