name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Last tag: $TAG"

          IFS='.' read -r major minor patch <<<"${TAG#v}"
          patch=$((patch + 1))
          NEW_TAG="v${major}.${minor}.${patch}"

          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/user-service:latest
            ${{ secrets.DOCKER_REGISTRY }}/user-service:${{ steps.version.outputs.new_tag }}
            ${{ secrets.DOCKER_REGISTRY }}/user-service:${{ github.sha }}

      - name: Create new git tag
        env:
          TAG: ${{ steps.version.outputs.new_tag }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG
          git push origin $TAG
